sudo: false
language: python

before_install:
  - docker run -d --rm -p 15672:15672 -p 5672:5672 -p 5671:5671 --name nameko-rabbitmq nameko/nameko-rabbitmq:3.6.6
  - docker cp nameko-rabbitmq:/srv/ssl certs

python:
  - '2.7'

install:
  - pip install tox

env:
  - TOX_ENV=py34-test

script:
  - tox -e $TOX_ENV

